services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./documents:/app/documents
      - ./logs:/app/logs
    env_file:
      - .env
    depends_on:
      - db
    command: ["/app/wait-for-it.sh", "db", "5432", "--", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  db:
    image: postgres:14
    container_name: facturacion_db
    environment:
      POSTGRES_USER: rdus
      POSTGRES_PASSWORD: 28325882
      POSTGRES_DB: facturacion
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: